controller_frequency: 3.0
recovery_behaviour_enabled: true
#controller_patience: 10
#planner_patiance: 5
#ocillation_timeout: 5

GlobalPlanner:
    #  use_dijkstra: false
    # use_grid_path: true
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  # default_tolerance: 0.5 # A tolerance on the goal point for the planner.
#DWAPlannerROS:

TebLocalPlannerROS:
    # Trajectory
   
    teb_autosize: True
    dt_ref: 0.3
    dt_hysteresis: 0.1
    global_plan_overwrite_orientation: True
   
    # Robot
   
    max_vel_x: 0.4
    max_vel_x_backwards: 0.2
    max_vel_theta: 0.3
    acc_lim_x: 0.5
    acc_lim_theta: 0.5
   
    # GoalTolerance
   
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.1
    free_goal_vel: False
   
    # Obstacles
   
    min_obstacle_dist: 0.4
    costmap_emergency_stop_dist: 0.3
    include_costmap_obstacles: True
    costmap_obstacles_front_only: True
    obstacle_poses_affected: 10
    line_obstacle_poses_affected: 25
    polygon_obstacle_poses_affected: 25
    costmap_converter_plugin: ""
    costmap_converter_spin_thread: True
    costmap_converter_rate: 5
   
    # Optimization
   
    no_inner_iterations: 5
    no_outer_iterations: 4
    optimization_activate: True
    optimization_verbose: False
    penalty_scale: 0.1
    penalty_epsilon: 0.1
    weight_max_vel_x: 2
    weight_max_vel_theta: 1
    weight_acc_lim_x: 1
    weight_acc_lim_theta: 1
    weight_kinematics_nh: 1000
    weight_kinematics_forward_drive: 1
    weight_optimaltime: 1
    weight_point_obstacle: 50
    weight_line_obstacle: 50
    weight_poly_obstacle: 50
    weight_dynamic_obstacle: 10
    alternative_time_cost: False
   
    # Homotopy Class Planner
   
    enable_homotopy_class_planning: True
    enable_multithreading: True
    simple_exploration: False
    max_number_classes: 5
    roadmap_graph_no_samples: 15
    roadmap_graph_area_width: 6
    h_signature_prescaler: 0.5
    h_signature_threshold: 0.01
    obstacle_keypoint_offset: 0.1
    obstacle_heading_threshold: 0.45
    visualize_hc_graph: False


TebLocalPlannerROS3:
    acc_lim_x: 1.0
    acc_lim_theta: 1.0
    max_vel_x: 3.0
    max_vel_x_backwards: 0.3
    max_vel_theta: 2.0
    dt_ref: 0.3
    dt_hysteresis: 0.2

    odom_topic: "/husky_velocity_controller/odom"
    map_frame: "/map"
    # weight_kinematics_forward_drive: 0.0
    # weight_poly_obstacle: 15.0
    # penalty_scale: 0.1 
    #enable_homotopy_class_planning: false

    # xy_goal_tolerance: 0.5


# TebLocalPlannerROS:
    #  acc_lim_x: 1.0
    # 
    # acc_lim_theter: 1.5
    #   max_vel_x: 2.0
    # max_vel_x_backwards: 2.0
    # max_vel_theta: 1.0
    # odom_topic: "/husky_velocity_controller/odom"
  

TebLocalPlannerROS2:
  # Robot configuration parameters  
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 4

  max_vel_x: 1.0
  max_vel_x_backwards: 1.0
  max_vel_y: 1.0
  max_vel_y_backwards: 1.0
  max_vel_theta: 1.5
  
  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.5
  # latch_xy_goal_tolerance: false

  # # Forward Simulation Parameters
#  sim_time: 2.0
#  sim_granularity: 0.02
#  vx_samples: 6
#  vy_samples: 0
#  vtheta_samples: 20
#  penalize_negative_x: false

  # # Trajectory scoring parameters
  #path_distance_bias: 25.0 # The weighting for how much the controller should stay close to the path it was given
  #goal_distance_bias: 30.0 # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  
  # occdist_scale: 0.01 # The weighting for how much the controller should attempt to avoid obstacles
  #forward_point_distance: 0.325 # The distance from the center point of the robot to place an additional scoring point, in meters
  # stop_time_buffer: 0.05  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint, in m/sop before a collision in order for a trajectory to be considered valid in seconds
 # scaling_speed: 0.1 # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  #max_scaling_factor: 0.2 # The maximum factor to scale the robot's footprint by

  # # Oscillation Prevention Parameters
  # oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
