footprint: [[-0.25, -0.33], [-0.25, 0.33], [0.25, 0.33], [0.25, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5
publish_frequency: 3.0
transform_tolerance: 1.5

resolution: 0.1

obstacle_range: 2.5
raytrace_range: 3.5

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.25
