// Generated by gencpp from file autonomous_commands/DriveToDefenseGoal.msg
// DO NOT EDIT!


#ifndef AUTONOMOUS_COMMANDS_MESSAGE_DRIVETODEFENSEGOAL_H
#define AUTONOMOUS_COMMANDS_MESSAGE_DRIVETODEFENSEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autonomous_commands
{
template <class ContainerAllocator>
struct DriveToDefenseGoal_
{
  typedef DriveToDefenseGoal_<ContainerAllocator> Type;

  DriveToDefenseGoal_()
    : defense(0)  {
    }
  DriveToDefenseGoal_(const ContainerAllocator& _alloc)
    : defense(0)  {
    }



   typedef int64_t _defense_type;
  _defense_type defense;




  typedef boost::shared_ptr< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DriveToDefenseGoal_

typedef ::autonomous_commands::DriveToDefenseGoal_<std::allocator<void> > DriveToDefenseGoal;

typedef boost::shared_ptr< ::autonomous_commands::DriveToDefenseGoal > DriveToDefenseGoalPtr;
typedef boost::shared_ptr< ::autonomous_commands::DriveToDefenseGoal const> DriveToDefenseGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autonomous_commands

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'autonomous_commands': ['/Barn2ROS/devel/share/autonomous_commands/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8bca81f6bdfcd545bd885ee932eac54";
  }

  static const char* value(const ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8bca81f6bdfcd54ULL;
  static const uint64_t static_value2 = 0x5bd885ee932eac54ULL;
};

template<class ContainerAllocator>
struct DataType< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autonomous_commands/DriveToDefenseGoal";
  }

  static const char* value(const ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
int64 defense\n\
";
  }

  static const char* value(const ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.defense);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DriveToDefenseGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autonomous_commands::DriveToDefenseGoal_<ContainerAllocator>& v)
  {
    s << indent << "defense: ";
    Printer<int64_t>::stream(s, indent + "  ", v.defense);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTONOMOUS_COMMANDS_MESSAGE_DRIVETODEFENSEGOAL_H
