// Generated by gencpp from file autonomous_commands/DriveToLowGoalGoal.msg
// DO NOT EDIT!


#ifndef AUTONOMOUS_COMMANDS_MESSAGE_DRIVETOLOWGOALGOAL_H
#define AUTONOMOUS_COMMANDS_MESSAGE_DRIVETOLOWGOALGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autonomous_commands
{
template <class ContainerAllocator>
struct DriveToLowGoalGoal_
{
  typedef DriveToLowGoalGoal_<ContainerAllocator> Type;

  DriveToLowGoalGoal_()
    : goal(0)  {
    }
  DriveToLowGoalGoal_(const ContainerAllocator& _alloc)
    : goal(0)  {
    }



   typedef int8_t _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DriveToLowGoalGoal_

typedef ::autonomous_commands::DriveToLowGoalGoal_<std::allocator<void> > DriveToLowGoalGoal;

typedef boost::shared_ptr< ::autonomous_commands::DriveToLowGoalGoal > DriveToLowGoalGoalPtr;
typedef boost::shared_ptr< ::autonomous_commands::DriveToLowGoalGoal const> DriveToLowGoalGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autonomous_commands

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'autonomous_commands': ['/home/sam/Barn2ROS/devel/share/autonomous_commands/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cad52981d420524454327e59958e6fe0";
  }

  static const char* value(const ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcad52981d4205244ULL;
  static const uint64_t static_value2 = 0x54327e59958e6fe0ULL;
};

template<class ContainerAllocator>
struct DataType< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autonomous_commands/DriveToLowGoalGoal";
  }

  static const char* value(const ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
int8 goal\n\
";
  }

  static const char* value(const ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DriveToLowGoalGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autonomous_commands::DriveToLowGoalGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    Printer<int8_t>::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTONOMOUS_COMMANDS_MESSAGE_DRIVETOLOWGOALGOAL_H
