MotorSender:
  send_wait_time: .000001
  round_to: 4
  message_prefix: "["
  message_suffix: "]"
  message_divider: ","
  
  controller_topics:
    - /lvelfront
    - /lvelcenter
    - /lvelrear
    - /rvelfront
    - /rvelcenter
    - /rvelrear
    
  network:
    ip: 10.7.51.109
    port: 9000
    
StatusReciever:
  imu_topic: /imu
  odom_frame: /odom
  lwheel_topic: /lwheel
  rwheel_topic: /rwheel
  
  network:
    ip: 0.0.0.0
    port: 6000
