; Auto-generated. Do not edit!


(cl:in-package autonomous_commands-msg)


;//! \htmlinclude AlignWithBallFeedback.msg.html

(cl:defclass <AlignWithBallFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass AlignWithBallFeedback (<AlignWithBallFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AlignWithBallFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AlignWithBallFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autonomous_commands-msg:<AlignWithBallFeedback> is deprecated: use autonomous_commands-msg:AlignWithBallFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AlignWithBallFeedback>) ostream)
  "Serializes a message object of type '<AlignWithBallFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AlignWithBallFeedback>) istream)
  "Deserializes a message object of type '<AlignWithBallFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AlignWithBallFeedback>)))
  "Returns string type for a message object of type '<AlignWithBallFeedback>"
  "autonomous_commands/AlignWithBallFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AlignWithBallFeedback)))
  "Returns string type for a message object of type 'AlignWithBallFeedback"
  "autonomous_commands/AlignWithBallFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AlignWithBallFeedback>)))
  "Returns md5sum for a message object of type '<AlignWithBallFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AlignWithBallFeedback)))
  "Returns md5sum for a message object of type 'AlignWithBallFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AlignWithBallFeedback>)))
  "Returns full string definition for message of type '<AlignWithBallFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AlignWithBallFeedback)))
  "Returns full string definition for message of type 'AlignWithBallFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AlignWithBallFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AlignWithBallFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'AlignWithBallFeedback
))
