; Auto-generated. Do not edit!


(cl:in-package autonomous_commands-msg)


;//! \htmlinclude DriveToDefenseFeedback.msg.html

(cl:defclass <DriveToDefenseFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DriveToDefenseFeedback (<DriveToDefenseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveToDefenseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveToDefenseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autonomous_commands-msg:<DriveToDefenseFeedback> is deprecated: use autonomous_commands-msg:DriveToDefenseFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveToDefenseFeedback>) ostream)
  "Serializes a message object of type '<DriveToDefenseFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveToDefenseFeedback>) istream)
  "Deserializes a message object of type '<DriveToDefenseFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveToDefenseFeedback>)))
  "Returns string type for a message object of type '<DriveToDefenseFeedback>"
  "autonomous_commands/DriveToDefenseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveToDefenseFeedback)))
  "Returns string type for a message object of type 'DriveToDefenseFeedback"
  "autonomous_commands/DriveToDefenseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveToDefenseFeedback>)))
  "Returns md5sum for a message object of type '<DriveToDefenseFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveToDefenseFeedback)))
  "Returns md5sum for a message object of type 'DriveToDefenseFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveToDefenseFeedback>)))
  "Returns full string definition for message of type '<DriveToDefenseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveToDefenseFeedback)))
  "Returns full string definition for message of type 'DriveToDefenseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveToDefenseFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveToDefenseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveToDefenseFeedback
))
