; Auto-generated. Do not edit!


(cl:in-package autonomous_commands-msg)


;//! \htmlinclude DriveForTimeFeedback.msg.html

(cl:defclass <DriveForTimeFeedback> (roslisp-msg-protocol:ros-message)
  ((time
    :reader time
    :initarg :time
    :type cl:integer
    :initform 0))
)

(cl:defclass DriveForTimeFeedback (<DriveForTimeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveForTimeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveForTimeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autonomous_commands-msg:<DriveForTimeFeedback> is deprecated: use autonomous_commands-msg:DriveForTimeFeedback instead.")))

(cl:ensure-generic-function 'time-val :lambda-list '(m))
(cl:defmethod time-val ((m <DriveForTimeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader autonomous_commands-msg:time-val is deprecated.  Use autonomous_commands-msg:time instead.")
  (time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveForTimeFeedback>) ostream)
  "Serializes a message object of type '<DriveForTimeFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'time)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveForTimeFeedback>) istream)
  "Deserializes a message object of type '<DriveForTimeFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'time) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveForTimeFeedback>)))
  "Returns string type for a message object of type '<DriveForTimeFeedback>"
  "autonomous_commands/DriveForTimeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveForTimeFeedback)))
  "Returns string type for a message object of type 'DriveForTimeFeedback"
  "autonomous_commands/DriveForTimeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveForTimeFeedback>)))
  "Returns md5sum for a message object of type '<DriveForTimeFeedback>"
  "50be640c11c45b7adcb0b6b7fbf3f928")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveForTimeFeedback)))
  "Returns md5sum for a message object of type 'DriveForTimeFeedback"
  "50be640c11c45b7adcb0b6b7fbf3f928")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveForTimeFeedback>)))
  "Returns full string definition for message of type '<DriveForTimeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%int64 time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveForTimeFeedback)))
  "Returns full string definition for message of type 'DriveForTimeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%int64 time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveForTimeFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveForTimeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveForTimeFeedback
    (cl:cons ':time (time msg))
))
