; Auto-generated. Do not edit!


(cl:in-package autonomous_commands-msg)


;//! \htmlinclude DriveForTimeResult.msg.html

(cl:defclass <DriveForTimeResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DriveForTimeResult (<DriveForTimeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveForTimeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveForTimeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autonomous_commands-msg:<DriveForTimeResult> is deprecated: use autonomous_commands-msg:DriveForTimeResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveForTimeResult>) ostream)
  "Serializes a message object of type '<DriveForTimeResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveForTimeResult>) istream)
  "Deserializes a message object of type '<DriveForTimeResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveForTimeResult>)))
  "Returns string type for a message object of type '<DriveForTimeResult>"
  "autonomous_commands/DriveForTimeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveForTimeResult)))
  "Returns string type for a message object of type 'DriveForTimeResult"
  "autonomous_commands/DriveForTimeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveForTimeResult>)))
  "Returns md5sum for a message object of type '<DriveForTimeResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveForTimeResult)))
  "Returns md5sum for a message object of type 'DriveForTimeResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveForTimeResult>)))
  "Returns full string definition for message of type '<DriveForTimeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveForTimeResult)))
  "Returns full string definition for message of type 'DriveForTimeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveForTimeResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveForTimeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveForTimeResult
))
