; Auto-generated. Do not edit!


(cl:in-package autonomous_commands-msg)


;//! \htmlinclude DriveToLowGoalGoal.msg.html

(cl:defclass <DriveToLowGoalGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type cl:fixnum
    :initform 0))
)

(cl:defclass DriveToLowGoalGoal (<DriveToLowGoalGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveToLowGoalGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveToLowGoalGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autonomous_commands-msg:<DriveToLowGoalGoal> is deprecated: use autonomous_commands-msg:DriveToLowGoalGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <DriveToLowGoalGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader autonomous_commands-msg:goal-val is deprecated.  Use autonomous_commands-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveToLowGoalGoal>) ostream)
  "Serializes a message object of type '<DriveToLowGoalGoal>"
  (cl:let* ((signed (cl:slot-value msg 'goal)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveToLowGoalGoal>) istream)
  "Deserializes a message object of type '<DriveToLowGoalGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveToLowGoalGoal>)))
  "Returns string type for a message object of type '<DriveToLowGoalGoal>"
  "autonomous_commands/DriveToLowGoalGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveToLowGoalGoal)))
  "Returns string type for a message object of type 'DriveToLowGoalGoal"
  "autonomous_commands/DriveToLowGoalGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveToLowGoalGoal>)))
  "Returns md5sum for a message object of type '<DriveToLowGoalGoal>"
  "cad52981d420524454327e59958e6fe0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveToLowGoalGoal)))
  "Returns md5sum for a message object of type 'DriveToLowGoalGoal"
  "cad52981d420524454327e59958e6fe0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveToLowGoalGoal>)))
  "Returns full string definition for message of type '<DriveToLowGoalGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int8 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveToLowGoalGoal)))
  "Returns full string definition for message of type 'DriveToLowGoalGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int8 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveToLowGoalGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveToLowGoalGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveToLowGoalGoal
    (cl:cons ':goal (goal msg))
))
