; Auto-generated. Do not edit!


(cl:in-package autonomous_commands-msg)


;//! \htmlinclude DriveToDefenseGoal.msg.html

(cl:defclass <DriveToDefenseGoal> (roslisp-msg-protocol:ros-message)
  ((defense
    :reader defense
    :initarg :defense
    :type cl:integer
    :initform 0))
)

(cl:defclass DriveToDefenseGoal (<DriveToDefenseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveToDefenseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveToDefenseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autonomous_commands-msg:<DriveToDefenseGoal> is deprecated: use autonomous_commands-msg:DriveToDefenseGoal instead.")))

(cl:ensure-generic-function 'defense-val :lambda-list '(m))
(cl:defmethod defense-val ((m <DriveToDefenseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader autonomous_commands-msg:defense-val is deprecated.  Use autonomous_commands-msg:defense instead.")
  (defense m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveToDefenseGoal>) ostream)
  "Serializes a message object of type '<DriveToDefenseGoal>"
  (cl:let* ((signed (cl:slot-value msg 'defense)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveToDefenseGoal>) istream)
  "Deserializes a message object of type '<DriveToDefenseGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'defense) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveToDefenseGoal>)))
  "Returns string type for a message object of type '<DriveToDefenseGoal>"
  "autonomous_commands/DriveToDefenseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveToDefenseGoal)))
  "Returns string type for a message object of type 'DriveToDefenseGoal"
  "autonomous_commands/DriveToDefenseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveToDefenseGoal>)))
  "Returns md5sum for a message object of type '<DriveToDefenseGoal>"
  "c8bca81f6bdfcd545bd885ee932eac54")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveToDefenseGoal)))
  "Returns md5sum for a message object of type 'DriveToDefenseGoal"
  "c8bca81f6bdfcd545bd885ee932eac54")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveToDefenseGoal>)))
  "Returns full string definition for message of type '<DriveToDefenseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int64 defense~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveToDefenseGoal)))
  "Returns full string definition for message of type 'DriveToDefenseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int64 defense~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveToDefenseGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveToDefenseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveToDefenseGoal
    (cl:cons ':defense (defense msg))
))
