; Auto-generated. Do not edit!


(cl:in-package autonomous_commands-msg)


;//! \htmlinclude DriveToLowGoalFeedback.msg.html

(cl:defclass <DriveToLowGoalFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DriveToLowGoalFeedback (<DriveToLowGoalFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveToLowGoalFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveToLowGoalFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autonomous_commands-msg:<DriveToLowGoalFeedback> is deprecated: use autonomous_commands-msg:DriveToLowGoalFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveToLowGoalFeedback>) ostream)
  "Serializes a message object of type '<DriveToLowGoalFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveToLowGoalFeedback>) istream)
  "Deserializes a message object of type '<DriveToLowGoalFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveToLowGoalFeedback>)))
  "Returns string type for a message object of type '<DriveToLowGoalFeedback>"
  "autonomous_commands/DriveToLowGoalFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveToLowGoalFeedback)))
  "Returns string type for a message object of type 'DriveToLowGoalFeedback"
  "autonomous_commands/DriveToLowGoalFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveToLowGoalFeedback>)))
  "Returns md5sum for a message object of type '<DriveToLowGoalFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveToLowGoalFeedback)))
  "Returns md5sum for a message object of type 'DriveToLowGoalFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveToLowGoalFeedback>)))
  "Returns full string definition for message of type '<DriveToLowGoalFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveToLowGoalFeedback)))
  "Returns full string definition for message of type 'DriveToLowGoalFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveToLowGoalFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveToLowGoalFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveToLowGoalFeedback
))
