; Auto-generated. Do not edit!


(cl:in-package autonomous_commands-msg)


;//! \htmlinclude DriveForTimeGoal.msg.html

(cl:defclass <DriveForTimeGoal> (roslisp-msg-protocol:ros-message)
  ((cmd
    :reader cmd
    :initarg :cmd
    :type geometry_msgs-msg:Twist
    :initform (cl:make-instance 'geometry_msgs-msg:Twist))
   (time
    :reader time
    :initarg :time
    :type cl:integer
    :initform 0))
)

(cl:defclass DriveForTimeGoal (<DriveForTimeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveForTimeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveForTimeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autonomous_commands-msg:<DriveForTimeGoal> is deprecated: use autonomous_commands-msg:DriveForTimeGoal instead.")))

(cl:ensure-generic-function 'cmd-val :lambda-list '(m))
(cl:defmethod cmd-val ((m <DriveForTimeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader autonomous_commands-msg:cmd-val is deprecated.  Use autonomous_commands-msg:cmd instead.")
  (cmd m))

(cl:ensure-generic-function 'time-val :lambda-list '(m))
(cl:defmethod time-val ((m <DriveForTimeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader autonomous_commands-msg:time-val is deprecated.  Use autonomous_commands-msg:time instead.")
  (time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveForTimeGoal>) ostream)
  "Serializes a message object of type '<DriveForTimeGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'cmd) ostream)
  (cl:let* ((signed (cl:slot-value msg 'time)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveForTimeGoal>) istream)
  "Deserializes a message object of type '<DriveForTimeGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'cmd) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'time) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveForTimeGoal>)))
  "Returns string type for a message object of type '<DriveForTimeGoal>"
  "autonomous_commands/DriveForTimeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveForTimeGoal)))
  "Returns string type for a message object of type 'DriveForTimeGoal"
  "autonomous_commands/DriveForTimeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveForTimeGoal>)))
  "Returns md5sum for a message object of type '<DriveForTimeGoal>"
  "7bf86b3e04e7a2304090f4bfc4969256")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveForTimeGoal)))
  "Returns md5sum for a message object of type 'DriveForTimeGoal"
  "7bf86b3e04e7a2304090f4bfc4969256")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveForTimeGoal>)))
  "Returns full string definition for message of type '<DriveForTimeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Twist cmd~%int64 time~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveForTimeGoal)))
  "Returns full string definition for message of type 'DriveForTimeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Twist cmd~%int64 time~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveForTimeGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'cmd))
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveForTimeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveForTimeGoal
    (cl:cons ':cmd (cmd msg))
    (cl:cons ':time (time msg))
))
