; Auto-generated. Do not edit!


(cl:in-package autonomous_commands-msg)


;//! \htmlinclude DriveToDefenseResult.msg.html

(cl:defclass <DriveToDefenseResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DriveToDefenseResult (<DriveToDefenseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveToDefenseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveToDefenseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autonomous_commands-msg:<DriveToDefenseResult> is deprecated: use autonomous_commands-msg:DriveToDefenseResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveToDefenseResult>) ostream)
  "Serializes a message object of type '<DriveToDefenseResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveToDefenseResult>) istream)
  "Deserializes a message object of type '<DriveToDefenseResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveToDefenseResult>)))
  "Returns string type for a message object of type '<DriveToDefenseResult>"
  "autonomous_commands/DriveToDefenseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveToDefenseResult)))
  "Returns string type for a message object of type 'DriveToDefenseResult"
  "autonomous_commands/DriveToDefenseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveToDefenseResult>)))
  "Returns md5sum for a message object of type '<DriveToDefenseResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveToDefenseResult)))
  "Returns md5sum for a message object of type 'DriveToDefenseResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveToDefenseResult>)))
  "Returns full string definition for message of type '<DriveToDefenseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveToDefenseResult)))
  "Returns full string definition for message of type 'DriveToDefenseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveToDefenseResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveToDefenseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveToDefenseResult
))
