; Auto-generated. Do not edit!


(cl:in-package autonomous_commands-msg)


;//! \htmlinclude DriveToLowGoalResult.msg.html

(cl:defclass <DriveToLowGoalResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DriveToLowGoalResult (<DriveToLowGoalResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DriveToLowGoalResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DriveToLowGoalResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autonomous_commands-msg:<DriveToLowGoalResult> is deprecated: use autonomous_commands-msg:DriveToLowGoalResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DriveToLowGoalResult>) ostream)
  "Serializes a message object of type '<DriveToLowGoalResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DriveToLowGoalResult>) istream)
  "Deserializes a message object of type '<DriveToLowGoalResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DriveToLowGoalResult>)))
  "Returns string type for a message object of type '<DriveToLowGoalResult>"
  "autonomous_commands/DriveToLowGoalResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DriveToLowGoalResult)))
  "Returns string type for a message object of type 'DriveToLowGoalResult"
  "autonomous_commands/DriveToLowGoalResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DriveToLowGoalResult>)))
  "Returns md5sum for a message object of type '<DriveToLowGoalResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DriveToLowGoalResult)))
  "Returns md5sum for a message object of type 'DriveToLowGoalResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DriveToLowGoalResult>)))
  "Returns full string definition for message of type '<DriveToLowGoalResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DriveToLowGoalResult)))
  "Returns full string definition for message of type 'DriveToLowGoalResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DriveToLowGoalResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DriveToLowGoalResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DriveToLowGoalResult
))
