# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 2.0
  cycle_time_error_threshold: 0.65

# Settings for ros_control hardware interface
hardware_interface:
    joints:
      - 'base_to_wheelrcenter'
      - 'base_to_wheelrfront'
      - 'base_to_wheelrrear'
      - 'base_to_wheellcenter'
      - 'base_to_wheellfront'
      - 'base_to_wheellrear'

# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

ddc:
  type: diff_drive_controller/DiffDriveController
  left_wheel:
    - 'base_to_wheelrcenter'
    - 'base_to_wheelrfront'
    - 'base_to_wheelrrear'
  right_wheel:
    - 'base_to_wheellcenter'
    - 'base_to_wheellfront'
    - 'base_to_wheellrear'
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 10.0  # m/s
      min_velocity           : -10.0 # m/s
      has_acceleration_limits: true
      max_acceleration       : 2  # m/s^2
      min_acceleration       : -2 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 10.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.0  # rad/s^2
